[package]
name = "abyme"
version = "0.1.0"
authors = ["Mitchell Riley <mitchell.v.riley@gmail.com>"]

[dependencies]
num = "*"

gfx = "0.16"
gfx_window_glutin = "*"
glutin = "*"

euclid = "*"
lyon = "*"

maplit = "*"
